### ISSUE TITLE
Text Glitch

### ISSUE THREAD

**Issue by Restioson** [PixleGame/Pixle#7]
Often while typing in the Multiplayer dialog, this happens:
https://i.imgur.com/IUGJPpx.png

Can be triggered by pressing cntrl + v.

EDIT: triggered when Plays.tv starts, even when it is set to Off.

**Comment by Gegy** [comment]
Can't reproduce

**Comment by Restioson** [comment]
(see edit)

**Comment by Restioson** [comment]
Closing as this seems dead.
